class CurrencyInfo {
  const CurrencyInfo({
    required this.code,
    required this.name,
    required this.symbol,
    required this.flag,
  });

  final String code;
  final String name;
  final String symbol;
  final String flag;

  String get label => '$flag $name';
  String get detail => '$code • $symbol';
}

const currencies = <CurrencyInfo>[
  CurrencyInfo(code: 'AED', name: 'UAE dirham', symbol: 'د.إ', flag: '🇦🇪'),
  CurrencyInfo(code: 'AFN', name: 'Afghan afghani', symbol: '؋', flag: '🇦🇫'),
  CurrencyInfo(code: 'ALL', name: 'Albanian lek', symbol: 'L', flag: '🇦🇱'),
  CurrencyInfo(code: 'AMD', name: 'Armenian dram', symbol: '֏', flag: '🇦🇲'),
  CurrencyInfo(
    code: 'ANG',
    name: 'Netherlands Antillean guilder',
    symbol: 'ƒ',
    flag: '🇨🇼',
  ),
  CurrencyInfo(code: 'AOA', name: 'Angolan kwanza', symbol: 'Kz', flag: '🇦🇴'),
  CurrencyInfo(code: 'ARS', name: 'Argentine peso', symbol: r'$', flag: '🇦🇷'),
  CurrencyInfo(
    code: 'AUD',
    name: 'Australian dollar',
    symbol: r'$',
    flag: '🇦🇺',
  ),
  CurrencyInfo(code: 'AWG', name: 'Aruban florin', symbol: 'ƒ', flag: '🇦🇼'),
  CurrencyInfo(
    code: 'AZN',
    name: 'Azerbaijani manat',
    symbol: '₼',
    flag: '🇦🇿',
  ),
  CurrencyInfo(
    code: 'BAM',
    name: 'Bosnia-Herzegovina convertible mark',
    symbol: 'KM',
    flag: '🇧🇦',
  ),
  CurrencyInfo(
    code: 'BBD',
    name: 'Barbadian dollar',
    symbol: r'$',
    flag: '🇧🇧',
  ),
  CurrencyInfo(
    code: 'BDT',
    name: 'Bangladeshi taka',
    symbol: '৳',
    flag: '🇧🇩',
  ),
  CurrencyInfo(code: 'BGN', name: 'Bulgarian lev', symbol: 'лв', flag: '🇧🇬'),
  CurrencyInfo(
    code: 'BHD',
    name: 'Bahraini dinar',
    symbol: '.د.ب',
    flag: '🇧🇭',
  ),
  CurrencyInfo(
    code: 'BIF',
    name: 'Burundian franc',
    symbol: 'FBu',
    flag: '🇧🇮',
  ),
  CurrencyInfo(
    code: 'BMD',
    name: 'Bermudian dollar',
    symbol: r'$',
    flag: '🇧🇲',
  ),
  CurrencyInfo(code: 'BND', name: 'Brunei dollar', symbol: r'$', flag: '🇧🇳'),
  CurrencyInfo(
    code: 'BOB',
    name: 'Bolivian boliviano',
    symbol: 'Bs.',
    flag: '🇧🇴',
  ),
  CurrencyInfo(
    code: 'BRL',
    name: 'Brazilian real',
    symbol: r'R$',
    flag: '🇧🇷',
  ),
  CurrencyInfo(
    code: 'BSD',
    name: 'Bahamian dollar',
    symbol: r'$',
    flag: '🇧🇸',
  ),
  CurrencyInfo(
    code: 'BTN',
    name: 'Bhutanese ngultrum',
    symbol: 'Nu.',
    flag: '🇧🇹',
  ),
  CurrencyInfo(code: 'BWP', name: 'Botswana pula', symbol: 'P', flag: '🇧🇼'),
  CurrencyInfo(
    code: 'BYN',
    name: 'Belarusian ruble',
    symbol: 'Br',
    flag: '🇧🇾',
  ),
  CurrencyInfo(code: 'BZD', name: 'Belize dollar', symbol: r'$', flag: '🇧🇿'),
  CurrencyInfo(
    code: 'CAD',
    name: 'Canadian dollar',
    symbol: r'$',
    flag: '🇨🇦',
  ),
  CurrencyInfo(
    code: 'CDF',
    name: 'Congolese franc',
    symbol: 'FC',
    flag: '🇨🇩',
  ),
  CurrencyInfo(code: 'CHF', name: 'Swiss franc', symbol: 'CHF', flag: '🇨🇭'),
  CurrencyInfo(code: 'CLP', name: 'Chilean peso', symbol: r'$', flag: '🇨🇱'),
  CurrencyInfo(code: 'CNY', name: 'Chinese yuan', symbol: '¥', flag: '🇨🇳'),
  CurrencyInfo(code: 'COP', name: 'Colombian peso', symbol: r'$', flag: '🇨🇴'),
  CurrencyInfo(
    code: 'CRC',
    name: 'Costa Rican colón',
    symbol: '₡',
    flag: '🇨🇷',
  ),
  CurrencyInfo(code: 'CUP', name: 'Cuban peso', symbol: r'$', flag: '🇨🇺'),
  CurrencyInfo(
    code: 'CVE',
    name: 'Cape Verdean escudo',
    symbol: r'$',
    flag: '🇨🇻',
  ),
  CurrencyInfo(code: 'CZK', name: 'Czech koruna', symbol: 'Kč', flag: '🇨🇿'),
  CurrencyInfo(
    code: 'DJF',
    name: 'Djiboutian franc',
    symbol: 'Fdj',
    flag: '🇩🇯',
  ),
  CurrencyInfo(code: 'DKK', name: 'Danish krone', symbol: 'kr', flag: '🇩🇰'),
  CurrencyInfo(code: 'DOP', name: 'Dominican peso', symbol: r'$', flag: '🇩🇴'),
  CurrencyInfo(
    code: 'DZD',
    name: 'Algerian dinar',
    symbol: 'د.ج',
    flag: '🇩🇿',
  ),
  CurrencyInfo(code: 'EGP', name: 'Egyptian pound', symbol: '£', flag: '🇪🇬'),
  CurrencyInfo(
    code: 'ERN',
    name: 'Eritrean nakfa',
    symbol: 'Nfk',
    flag: '🇪🇷',
  ),
  CurrencyInfo(code: 'ETB', name: 'Ethiopian birr', symbol: 'Br', flag: '🇪🇹'),
  CurrencyInfo(code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺'),
  CurrencyInfo(code: 'FJD', name: 'Fijian dollar', symbol: r'$', flag: '🇫🇯'),
  CurrencyInfo(
    code: 'FKP',
    name: 'Falkland Islands pound',
    symbol: '£',
    flag: '🇫🇰',
  ),
  CurrencyInfo(code: 'GBP', name: 'British pound', symbol: '£', flag: '🇬🇧'),
  CurrencyInfo(code: 'GEL', name: 'Georgian lari', symbol: '₾', flag: '🇬🇪'),
  CurrencyInfo(code: 'GHS', name: 'Ghanaian cedi', symbol: '₵', flag: '🇬🇭'),
  CurrencyInfo(code: 'GIP', name: 'Gibraltar pound', symbol: '£', flag: '🇬🇮'),
  CurrencyInfo(code: 'GMD', name: 'Gambian dalasi', symbol: 'D', flag: '🇬🇲'),
  CurrencyInfo(code: 'GNF', name: 'Guinean franc', symbol: 'FG', flag: '🇬🇳'),
  CurrencyInfo(
    code: 'GTQ',
    name: 'Guatemalan quetzal',
    symbol: 'Q',
    flag: '🇬🇹',
  ),
  CurrencyInfo(
    code: 'GYD',
    name: 'Guyanese dollar',
    symbol: r'$',
    flag: '🇬🇾',
  ),
  CurrencyInfo(
    code: 'HKD',
    name: 'Hong Kong dollar',
    symbol: r'$',
    flag: '🇭🇰',
  ),
  CurrencyInfo(
    code: 'HNL',
    name: 'Honduran lempira',
    symbol: 'L',
    flag: '🇭🇳',
  ),
  CurrencyInfo(code: 'HTG', name: 'Haitian gourde', symbol: 'G', flag: '🇭🇹'),
  CurrencyInfo(
    code: 'HUF',
    name: 'Hungarian forint',
    symbol: 'Ft',
    flag: '🇭🇺',
  ),
  CurrencyInfo(
    code: 'IDR',
    name: 'Indonesian rupiah',
    symbol: 'Rp',
    flag: '🇮🇩',
  ),
  CurrencyInfo(
    code: 'ILS',
    name: 'Israeli new shekel',
    symbol: '₪',
    flag: '🇮🇱',
  ),
  CurrencyInfo(code: 'INR', name: 'Indian rupee', symbol: '₹', flag: '🇮🇳'),
  CurrencyInfo(code: 'IQD', name: 'Iraqi dinar', symbol: 'ع.د', flag: '🇮🇶'),
  CurrencyInfo(code: 'IRR', name: 'Iranian rial', symbol: '﷼', flag: '🇮🇷'),
  CurrencyInfo(
    code: 'ISK',
    name: 'Icelandic króna',
    symbol: 'kr',
    flag: '🇮🇸',
  ),
  CurrencyInfo(
    code: 'JMD',
    name: 'Jamaican dollar',
    symbol: r'$',
    flag: '🇯🇲',
  ),
  CurrencyInfo(
    code: 'JOD',
    name: 'Jordanian dinar',
    symbol: 'د.ا',
    flag: '🇯🇴',
  ),
  CurrencyInfo(code: 'JPY', name: 'Japanese yen', symbol: '¥', flag: '🇯🇵'),
  CurrencyInfo(
    code: 'KES',
    name: 'Kenyan shilling',
    symbol: 'KSh',
    flag: '🇰🇪',
  ),
  CurrencyInfo(
    code: 'KGS',
    name: 'Kyrgyzstani som',
    symbol: 'сом',
    flag: '🇰🇬',
  ),
  CurrencyInfo(code: 'KHR', name: 'Cambodian riel', symbol: '៛', flag: '🇰🇭'),
  CurrencyInfo(code: 'KMF', name: 'Comorian franc', symbol: 'CF', flag: '🇰🇲'),
  CurrencyInfo(
    code: 'KRW',
    name: 'South Korean won',
    symbol: '₩',
    flag: '🇰🇷',
  ),
  CurrencyInfo(code: 'KWD', name: 'Kuwaiti dinar', symbol: 'د.ك', flag: '🇰🇼'),
  CurrencyInfo(
    code: 'KYD',
    name: 'Cayman Islands dollar',
    symbol: r'$',
    flag: '🇰🇾',
  ),
  CurrencyInfo(
    code: 'KZT',
    name: 'Kazakhstani tenge',
    symbol: '₸',
    flag: '🇰🇿',
  ),
  CurrencyInfo(code: 'LAK', name: 'Lao kip', symbol: '₭', flag: '🇱🇦'),
  CurrencyInfo(
    code: 'LBP',
    name: 'Lebanese pound',
    symbol: 'ل.ل',
    flag: '🇱🇧',
  ),
  CurrencyInfo(
    code: 'LKR',
    name: 'Sri Lankan rupee',
    symbol: 'Rs',
    flag: '🇱🇰',
  ),
  CurrencyInfo(
    code: 'LRD',
    name: 'Liberian dollar',
    symbol: r'$',
    flag: '🇱🇷',
  ),
  CurrencyInfo(code: 'LSL', name: 'Lesotho loti', symbol: 'L', flag: '🇱🇸'),
  CurrencyInfo(code: 'LYD', name: 'Libyan dinar', symbol: 'ل.د', flag: '🇱🇾'),
  CurrencyInfo(
    code: 'MAD',
    name: 'Moroccan dirham',
    symbol: 'د.م.',
    flag: '🇲🇦',
  ),
  CurrencyInfo(code: 'MDL', name: 'Moldovan leu', symbol: 'L', flag: '🇲🇩'),
  CurrencyInfo(
    code: 'MGA',
    name: 'Malagasy ariary',
    symbol: 'Ar',
    flag: '🇲🇬',
  ),
  CurrencyInfo(
    code: 'MKD',
    name: 'Macedonian denar',
    symbol: 'ден',
    flag: '🇲🇰',
  ),
  CurrencyInfo(code: 'MMK', name: 'Myanmar kyat', symbol: 'K', flag: '🇲🇲'),
  CurrencyInfo(
    code: 'MNT',
    name: 'Mongolian tögrög',
    symbol: '₮',
    flag: '🇲🇳',
  ),
  CurrencyInfo(code: 'MOP', name: 'Macanese pataca', symbol: 'P', flag: '🇲🇴'),
  CurrencyInfo(
    code: 'MRU',
    name: 'Mauritanian ouguiya',
    symbol: 'UM',
    flag: '🇲🇷',
  ),
  CurrencyInfo(code: 'MUR', name: 'Mauritian rupee', symbol: '₨', flag: '🇲🇺'),
  CurrencyInfo(
    code: 'MVR',
    name: 'Maldivian rufiyaa',
    symbol: 'Rf',
    flag: '🇲🇻',
  ),
  CurrencyInfo(
    code: 'MWK',
    name: 'Malawian kwacha',
    symbol: 'MK',
    flag: '🇲🇼',
  ),
  CurrencyInfo(code: 'MXN', name: 'Mexican peso', symbol: r'$', flag: '🇲🇽'),
  CurrencyInfo(
    code: 'MYR',
    name: 'Malaysian ringgit',
    symbol: 'RM',
    flag: '🇲🇾',
  ),
  CurrencyInfo(
    code: 'MZN',
    name: 'Mozambican metical',
    symbol: 'MT',
    flag: '🇲🇿',
  ),
  CurrencyInfo(
    code: 'NAD',
    name: 'Namibian dollar',
    symbol: r'$',
    flag: '🇳🇦',
  ),
  CurrencyInfo(code: 'NGN', name: 'Nigerian naira', symbol: '₦', flag: '🇳🇬'),
  CurrencyInfo(
    code: 'NIO',
    name: 'Nicaraguan córdoba',
    symbol: r'C$',
    flag: '🇳🇮',
  ),
  CurrencyInfo(
    code: 'NOK',
    name: 'Norwegian krone',
    symbol: 'kr',
    flag: '🇳🇴',
  ),
  CurrencyInfo(code: 'NPR', name: 'Nepalese rupee', symbol: '₨', flag: '🇳🇵'),
  CurrencyInfo(
    code: 'NZD',
    name: 'New Zealand dollar',
    symbol: r'$',
    flag: '🇳🇿',
  ),
  CurrencyInfo(code: 'OMR', name: 'Omani rial', symbol: 'ر.ع.', flag: '🇴🇲'),
  CurrencyInfo(
    code: 'PAB',
    name: 'Panamanian balboa',
    symbol: 'B/.',
    flag: '🇵🇦',
  ),
  CurrencyInfo(code: 'PEN', name: 'Peruvian sol', symbol: 'S/', flag: '🇵🇪'),
  CurrencyInfo(
    code: 'PGK',
    name: 'Papua New Guinean kina',
    symbol: 'K',
    flag: '🇵🇬',
  ),
  CurrencyInfo(code: 'PHP', name: 'Philippine peso', symbol: '₱', flag: '🇵🇭'),
  CurrencyInfo(code: 'PKR', name: 'Pakistani rupee', symbol: '₨', flag: '🇵🇰'),
  CurrencyInfo(code: 'PLN', name: 'Polish złoty', symbol: 'zł', flag: '🇵🇱'),
  CurrencyInfo(
    code: 'PYG',
    name: 'Paraguayan guaraní',
    symbol: '₲',
    flag: '🇵🇾',
  ),
  CurrencyInfo(code: 'QAR', name: 'Qatari riyal', symbol: 'ر.ق', flag: '🇶🇦'),
  CurrencyInfo(code: 'RON', name: 'Romanian leu', symbol: 'lei', flag: '🇷🇴'),
  CurrencyInfo(
    code: 'RSD',
    name: 'Serbian dinar',
    symbol: 'дин.',
    flag: '🇷🇸',
  ),
  CurrencyInfo(code: 'RUB', name: 'Russian ruble', symbol: '₽', flag: '🇷🇺'),
  CurrencyInfo(code: 'RWF', name: 'Rwandan franc', symbol: 'FRw', flag: '🇷🇼'),
  CurrencyInfo(code: 'SAR', name: 'Saudi riyal', symbol: 'ر.س', flag: '🇸🇦'),
  CurrencyInfo(
    code: 'SBD',
    name: 'Solomon Islands dollar',
    symbol: r'$',
    flag: '🇸🇧',
  ),
  CurrencyInfo(
    code: 'SCR',
    name: 'Seychellois rupee',
    symbol: '₨',
    flag: '🇸🇨',
  ),
  CurrencyInfo(
    code: 'SDG',
    name: 'Sudanese pound',
    symbol: 'ج.س.',
    flag: '🇸🇩',
  ),
  CurrencyInfo(code: 'SEK', name: 'Swedish krona', symbol: 'kr', flag: '🇸🇪'),
  CurrencyInfo(
    code: 'SGD',
    name: 'Singapore dollar',
    symbol: r'$',
    flag: '🇸🇬',
  ),
  CurrencyInfo(
    code: 'SHP',
    name: 'Saint Helena pound',
    symbol: '£',
    flag: '🇸🇭',
  ),
  CurrencyInfo(
    code: 'SLE',
    name: 'Sierra Leonean leone',
    symbol: 'Le',
    flag: '🇸🇱',
  ),
  CurrencyInfo(
    code: 'SOS',
    name: 'Somali shilling',
    symbol: 'Sh',
    flag: '🇸🇴',
  ),
  CurrencyInfo(
    code: 'SRD',
    name: 'Surinamese dollar',
    symbol: r'$',
    flag: '🇸🇷',
  ),
  CurrencyInfo(
    code: 'SSP',
    name: 'South Sudanese pound',
    symbol: '£',
    flag: '🇸🇸',
  ),
  CurrencyInfo(
    code: 'STN',
    name: 'São Tomé and Príncipe dobra',
    symbol: 'Db',
    flag: '🇸🇹',
  ),
  CurrencyInfo(code: 'SYP', name: 'Syrian pound', symbol: '£', flag: '🇸🇾'),
  CurrencyInfo(
    code: 'SZL',
    name: 'Eswatini lilangeni',
    symbol: 'L',
    flag: '🇸🇿',
  ),
  CurrencyInfo(code: 'THB', name: 'Thai baht', symbol: '฿', flag: '🇹🇭'),
  CurrencyInfo(
    code: 'TJS',
    name: 'Tajikistani somoni',
    symbol: 'ЅМ',
    flag: '🇹🇯',
  ),
  CurrencyInfo(
    code: 'TMT',
    name: 'Turkmenistani manat',
    symbol: 'm',
    flag: '🇹🇲',
  ),
  CurrencyInfo(
    code: 'TND',
    name: 'Tunisian dinar',
    symbol: 'د.ت',
    flag: '🇹🇳',
  ),
  CurrencyInfo(
    code: 'TOP',
    name: 'Tongan paʻanga',
    symbol: r'T$',
    flag: '🇹🇴',
  ),
  CurrencyInfo(code: 'TRY', name: 'Turkish lira', symbol: '₺', flag: '🇹🇷'),
  CurrencyInfo(
    code: 'TTD',
    name: 'Trinidad and Tobago dollar',
    symbol: r'$',
    flag: '🇹🇹',
  ),
  CurrencyInfo(
    code: 'TWD',
    name: 'New Taiwan dollar',
    symbol: r'$',
    flag: '🇹🇼',
  ),
  CurrencyInfo(
    code: 'TZS',
    name: 'Tanzanian shilling',
    symbol: 'Sh',
    flag: '🇹🇿',
  ),
  CurrencyInfo(
    code: 'UAH',
    name: 'Ukrainian hryvnia',
    symbol: '₴',
    flag: '🇺🇦',
  ),
  CurrencyInfo(
    code: 'UGX',
    name: 'Ugandan shilling',
    symbol: 'USh',
    flag: '🇺🇬',
  ),
  CurrencyInfo(code: 'USD', name: 'US dollar', symbol: r'$', flag: '🇺🇸'),
  CurrencyInfo(code: 'UYU', name: 'Uruguayan peso', symbol: r'$', flag: '🇺🇾'),
  CurrencyInfo(
    code: 'UZS',
    name: 'Uzbekistani som',
    symbol: 'soʻm',
    flag: '🇺🇿',
  ),
  CurrencyInfo(
    code: 'VES',
    name: 'Venezuelan bolívar',
    symbol: 'Bs.',
    flag: '🇻🇪',
  ),
  CurrencyInfo(code: 'VND', name: 'Vietnamese đồng', symbol: '₫', flag: '🇻🇳'),
  CurrencyInfo(code: 'VUV', name: 'Vanuatu vatu', symbol: 'VT', flag: '🇻🇺'),
  CurrencyInfo(code: 'WST', name: 'Samoan tālā', symbol: r'T$', flag: '🇼🇸'),
  CurrencyInfo(
    code: 'XAF',
    name: 'Central African CFA franc',
    symbol: 'FCFA',
    flag: '🇨🇲',
  ),
  CurrencyInfo(
    code: 'XCD',
    name: 'East Caribbean dollar',
    symbol: r'$',
    flag: '🇦🇬',
  ),
  CurrencyInfo(
    code: 'XOF',
    name: 'West African CFA franc',
    symbol: 'CFA',
    flag: '🇸🇳',
  ),
  CurrencyInfo(code: 'XPF', name: 'CFP franc', symbol: '₣', flag: '🇵🇫'),
  CurrencyInfo(code: 'YER', name: 'Yemeni rial', symbol: '﷼', flag: '🇾🇪'),
  CurrencyInfo(
    code: 'ZAR',
    name: 'South African rand',
    symbol: 'R',
    flag: '🇿🇦',
  ),
  CurrencyInfo(code: 'ZMW', name: 'Zambian kwacha', symbol: 'ZK', flag: '🇿🇲'),
  CurrencyInfo(code: 'ZWG', name: 'Zimbabwe Gold', symbol: 'ZiG', flag: '🇿🇼'),
];

CurrencyInfo currencyInfoFor(String code) {
  return currencies.firstWhere(
    (currency) => currency.code == code,
    orElse: () =>
        CurrencyInfo(code: code, name: code, symbol: code, flag: '🏳️'),
  );
}
